### ISSUE TITLE
zoomable into the gantt graph

### ISSUE THREAD

**Issue by Andi1986** [marcusolsson/grafana-gantt-panel#10]
in other graphs of grafana it is possible to zoom in, inside the graph for having a shorter time range by just marking a certain part of the graph. This should also be possible for the Gantt graph.

**Comment by marcusolsson** [comment]
This is definitely a requirement. I will have to do some research on how to do this first though.

**Comment by marcusolsson** [comment]
Available in 0.4.0 🎉  Please try it and report any issues!

**Comment by Andi1986** [comment]
hi, maybe i just behave clumsy, but how does it work ? i cannot zoom in by draging the mouse

**Comment by marcusolsson** [comment]
Are you trying to zoom when grouping activities? Currently, zooming is only supported for absolute time ranges, whereas Group by switches to relative time. 

See [this issue](https://github.com/marcusolsson/grafana-gantt-panel/issues/11) for more information.

**Comment by Andi1986** [comment]
is it possible to _**not**_ group activities ? i think the Group by Dimension is mandatory, correct ? i cant remove the group by neither anyways.
i have tried both, relative and absolute time ranges, neither works

**Comment by Andi1986** [comment]
ok i found, group by seems to be not mandatory initially, but once it is set, its not possible to remove the group by , maybe that is a different issue :)
