### ISSUE TITLE
Zoom In not working when the "Group By" field is used.

### ISSUE THREAD

**Issue by patrik2991** [marcusolsson/grafana-gantt-panel#11]
Hi!
I just noticed that when the "Group By" field is used, the Zoom In feature is not working.
I don't know if it's intended because of the varying timeranges, but if yes, than maybe there should be an option to not auto-align the chart between the first start and the last finish, just use the selected time range.
Thank you for your efforts!

**Comment by marcusolsson** [comment]
Thank you for the feedback! My reasoning has been that when you're grouping activities, you likely want to compare them with similar runs. For example, I'm planning to allow duration on the X-axis when using Group by.

Without the relative time range, Group by is essentially just a filter which could be solved with dashboard variables. 

The other option is to have a separate option for toggling between relative and absolute time. 

Could you share more about your use case so I can understand it better?

**Comment by patrik2991** [comment]
I just used it on the panel because it wasn't relevant dashboard-wide.
It's not a problem, just I think in this case it should be noted somewhere, that it just works if the grouping is not used.
