### ISSUE TITLE
Possibility to display the chart sorted by text field

### ISSUE THREAD

**Issue by AnastasiaBlack** [marcusolsson/grafana-gantt-panel#15]
Hello! First of all, thank you very much for the work and effort you put into this plugin, it's really helpful. 

We use Prometheus queries to get the start time and the end time of each task, and according to the Grafana Query Inspector the raw results of the queries are sorted the way we want it, but on the chart itself, it seems that the data is reordered by Start Time. 

The question is, is there an opportunity to display blocks of data sorted by the text field (taking as an example the picture from the plugin overview https://grafana.com/grafana/plugins/marcusolsson-gantt-panel to display the blocks not ordered by start time( extract, transform, load), but ordered alphabetically by text field: extract, load, transform )?  

Thank you very much!

**Comment by marcusolsson** [comment]
Thank you for trying out the plugin, and for taking the time to suggest how to improve it!

I don't see any problems adding this 👍
