### ISSUE TITLE
Limit Y-axis to relevant values only

### ISSUE THREAD

**Issue by DetroitSteelTreating** [marcusolsson/grafana-gantt-panel#19]
First of all, thanks for developing a really great plugin.  In addition to the issues already mentioned, it seems having the y-axis values reduced to only display the relevant text events (over the timeline being viewed) needs to be fixed.  See these screenshots.  One is a 30-day view of work orders run sequentially (https://photos.app.goo.gl/moMTrrFvjDEc6NwX6), and the second is a zoomed in view of one 24-hour subset of these 30 days (https://photos.app.goo.gl/svgZ9KDqaSCBdBw17).  The second view should not contain all of the work orders run outside of this one 24-hour window.

**Comment by marcusolsson** [comment]
Thanks for reporting this! I think it makes sense to only display tasks that were ongoing during the selected time interval. It's a pretty simple fix so I'll be able to get this updated in the coming days.

**Comment by DetroitSteelTreating** [comment]
Marcus: I see this is now closed.  Do I need to reinstall the plug in for it to work?  So far, on my version, it appears the same as it did when I first raised the issue.

**Comment by marcusolsson** [comment]
It was fixed, but not released. I just published 0.6.1 which contains the fix. Please try it out.

**Comment by DetroitSteelTreating** [comment]
Got it working beautifully now.  Thank you again!
