### ISSUE TITLE
Color of the entire bar chart

### ISSUE THREAD

**Issue by Healone** [marcusolsson/grafana-gantt-panel#20]
Hello,

I would like to know if it was possible to change the color of the bar into the gantt chart.
After several hours of searching about that, I end up sending you a little message to looking for help.

We got a blue light theme between all of our grafana dashboard and the default green pose a problem.
![Capture](https://user-images.githubusercontent.com/76242786/109662229-bba38780-7b62-11eb-8d39-01b14371236b.PNG)

Beside of that, I enjoy your work and I wanted to thank you for this insance panel plugin !

Looking forward for your response, have a nice day!

**Comment by marcusolsson** [comment]
Hey, unfortunately not at this time. I'll probably add this while I implement #8, so please add any color-related questions/feature requests in that issue.

**Comment by marcusolsson** [comment]
Closing in favor of #8
