### ISSUE TITLE
Limitable bar height

### ISSUE THREAD

**Issue by ymmt07039** [marcusolsson/grafana-gantt-panel#21]
Hello, thank you for develop this useful panel.

I think if bar height is limitable the panel will be easier to see.

my idea:
```javascript
  const scalePadding = Math.max(
    (1 - options.limit * taskLabels.length) / (1 + options.limit),
    0
  )

  const scaleY = d3.scaleBand().domain(taskLabels).range([0, chartHeight]).padding(scalePadding)
```
`options.limit` ranged 0.00 to 1.00, bandWidth limited to `options.limit * chartHight`.

any other opinions are welcome.

in my use case, gantt panel is repeated vertically and the number of tasks is variable.
I made example image:
![screenshot](https://user-images.githubusercontent.com/49381624/110275031-9952b380-8013-11eb-87ed-49b599fc2278.png)

**Comment by marcusolsson** [comment]
Thanks for the suggestion! I'd be happy to improve the current task height. 

Do you think there's a way we could accomplish this without adding another option? I think most users just want "something that works", and not have to configure this. 

It seems like the main problem is that the task height is too big when there are fewer tasks. Could we maybe limit the task height to a percentage of the chart height?

**Comment by ymmt07039** [comment]
Yes, I think 25% of chart height is seemed good.
Tall panel will expect many tasks, so no limit needed.

```javascript
  const scalePadding = Math.max(
    (1 - 0.25 * taskLabels.length) / (1 + 0.25),
    0
  )
```
Is there any other opinion?

**Comment by marcusolsson** [comment]
Looks good to me! Since you already have the implementation, would you like to submit a PR for this?

**Comment by ymmt07039** [comment]
Thank you!
