### ISSUE TITLE
Loading plugin fails (This plugin requires a more recent version of Grafana (>=7.0.3) - running 7.5

### ISSUE THREAD

**Issue by dpunzeng** [marcusolsson/grafana-gantt-panel#23]
Hi, I ad the issue with 7.4, now I upgraded to 7.5 beta - still says
>>
Error loading: marcusolsson-gantt-panel
This plugin requires a more recent version of Grafana (>=7.0.3).
<<

Any help please - thx Dieter

**Comment by marcusolsson** [comment]
The check didn't include prereleases such as beta1. Fix will be included in next release.
