### ISSUE TITLE
Display multiple bars on one line

### ISSUE THREAD

**Issue by jamessewell** [marcusolsson/grafana-gantt-panel#29]
Hi,

I have slightly different requirements to a standard Gantt chart - but I do wonder if it would be a trivial change to this plugin.

I am capturing states changes of different items. Each item id can only be in a single state at a single time.

My data will look like this:

`id, start_ts, end_ts, label`

I want to visualize it with each id on a row, with different colours per label.

Is this possible / how hard would it be to mod your plugin (happy to help)?

**Comment by jamessewell** [comment]
Oh you can do this!

**Comment by marcusolsson** [comment]
Yeah, although I'll admit it's more of a happy accident rather than a conscious design choice 😅
