### ISSUE TITLE
Option to not display y axis labels

### ISSUE THREAD

**Issue by jamessewell** [marcusolsson/grafana-gantt-panel#30]
This would be helpful when there are a lot of bars - I can hover over to see the names if I need to.

I'm not sure if Grafana allows this though?

**Comment by marcusolsson** [comment]
I'm using SVG/D3.js to build the graph rather than using the built-in one so should be a simple fix.

**Comment by jamessewell** [comment]
Amazing - really excited about this plugin, items great
