### ISSUE TITLE
Nothing plotted when too many values on y axis

### ISSUE THREAD

**Issue by jamessewell** [marcusolsson/grafana-gantt-panel#32]
I know that this is an impossible issue to fix totally - after a certain point there aren't enough pixels to plot everything!

At the moment when this happens I just get nothing on my graph (usually around 100 - 150 items), can I suggest one of two options:

a) Plot what you can and indicate that it's a partial plot
b) Just display that plotting failed due to too many y axis values, and suggesting the user reduces the cardinality or zooms in

**Comment by marcusolsson** [comment]
Good suggestion! Never tried plotting that many tasks before!

I'm thinking it's probably safer to go with b) rather than showing incomplete data. Also it feels easier to go from showing more than showing less, if we realize we made the wrong choice. WDYT?

**Comment by jamessewell** [comment]
Yes, agree

**Comment by deepakg3** [comment]
I have a similar case as well, when the y axis is large, the chart isn't any readable. I was thinking if we can have a vertical scrollbar in the panel that way the chart is readable and can fit many events. Does this sound good and is it any doable?

**Comment by marcusolsson** [comment]
I've published 0.7.1 with a fix for this. I've gone with option b) suggested by @jamessewell as I think it minimizes the number of unwanted surprises.

@deepakg3 I think it would be nice with a scrollbar, but I don't want users to have to scroll to see the X-axis. We could look into only scrolling the contents within the axes, but that might be tricky to do with SVG. If the current notice for too many tasks isn't cutting it for you, please create another feature request.
