### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by ecgg** [marcusolsson/grafana-gantt-panel#4]
Hi,

Thank you for creating this plugin; my managers are salivating over it.

I had one request; would it be possible for the timeline on the X-axis to respect the date format set in the Grafana config because this leads otherwise to distinct date styles between graphs.

![2021-01-28 08_57_23-Window](https://user-images.githubusercontent.com/27764963/106107457-3e41bd00-6147-11eb-9b89-7b747ba5b2da.png)

**Comment by marcusolsson** [comment]
That's hilarious 🤣 

Proper date formatting is definitely on the roadmap. I'll get working on it 👍 

That being said, I don't really have any planned features at this point. Mostly because I'd like to know more about how people are using it before I start adding things. Please let me know if there's anything else you think would improve the plugin.

**Comment by ecgg** [comment]
At the moment I use it to visualize ECDC [Data on country response measures to COVID-19](https://www.ecdc.europa.eu/en/publications-data/download-data-response-measures-covid-19). Download CSV via script, inject into MySQL and then let your plugin show. The data was almost made for this plugin.

![2021-01-28 09_54_29-Window](https://user-images.githubusercontent.com/27764963/106113648-0179c400-614f-11eb-8b41-5732d773f4d5.png)

But as I said, at least one manager noticed the plugin and he is already is rummaging in his excel files.

**Comment by marcusolsson** [comment]
Thanks for sharing your use case (and the data). The screenshot does look a little weird, since activities should be sorted by start time. I'll see if I can load the data and play around with it a bit.

**Comment by marcusolsson** [comment]
Very cool!

<img width="1440" alt="Screen Shot 2021-01-28 at 10 55 21" src="https://user-images.githubusercontent.com/8396880/106121025-5faaa500-6157-11eb-980e-cbf5b23e70fd.png">

**Comment by marcusolsson** [comment]
Just published v0.3.0, with improved date formatting. 

FYI I also noticed that activities without end date generated errors. As a result, the panel shows incomplete data. I added a fix so that null values instead extend to the extent of the graph.

**Comment by ecgg** [comment]
It's beautiful - thank you very much
