### ISSUE TITLE
Data which starts outside display window not drawn

### ISSUE THREAD

**Issue by jamessewell** [marcusolsson/grafana-gantt-panel#40]
Thanks for all the updates recently!

I just noticed that if I have elements returned from my query which start outside the current time window (but continue into it), it seems that they won’t be drawn.

This is often really desirable.

Thanks again!

**Comment by marcusolsson** [comment]
This is already implemented, though looking at the [code](https://github.com/marcusolsson/grafana-gantt-panel/blob/955b4232873d3774a1ea3ce3f8d52f43cfc1b9e9/src/GanttChart.tsx#L139-L140) it seems like there's a missing case for when the start time of the task is before the start of the interval _AND_ the end time of the task is after the end of the interval. Could you confirm that this is the issue you're seeing?

**Comment by jamessewell** [comment]
Yes - now I look into this more that is the edge case!
