### ISSUE TITLE
How to use `Data links`

### ISSUE THREAD

**Issue by n-arakawa** [marcusolsson/grafana-gantt-panel#49]
Each GanttTask  component seem to have datalink capability.
However I can't find out how to invoke the link.
Please add the link to tool tips.

**Comment by marcusolsson** [comment]
I [just discovered](https://github.com/marcusolsson/grafana-treemap-panel/issues/24) that Data Links support seems to be broken in Grafana 8.

**Comment by marcusolsson** [comment]
Fixed in v0.7.4.
