### ISSUE TITLE
Millisecond Precision

### ISSUE THREAD

**Issue by vaughanbrittonsage** [marcusolsson/grafana-gantt-panel#5]
Hi, Sorry to bother you. Thanks for the recent changes to support selecting any field it has enabled me to make further progress with the plugin. However I have a issue due to my use case,  my data is at millisecond precision

e.g.

Started:  `2021-02-01T18:19:41.1228782Z`
Completed: `2021-02-01T18:19:41.1382584Z`

This results in all items displayed on the gantt panel as the same size with the same start/end position for the same second, I'm thinking this is because the panel only displays items down to second precision? I was wondering if this is expected, and if it could be changed to support millisecond precision?

Thanks

**Comment by marcusolsson** [comment]
Thanks for trying out the Gantt panel! ❤️ 

I just tried and I'm able to visualize sub-second intervals:

<img width="711" alt="Screen Shot 2021-02-02 at 07 21 59" src="https://user-images.githubusercontent.com/8396880/106560469-59d20c80-6527-11eb-9a4c-b304489c3ff7.png">

I suspect it's your data source that drops the milliseconds. 

Could you go to the panel inspector and make sure that your data is milliseconds accuracy?

<img width="333" alt="Screen Shot 2021-02-02 at 07 19 44" src="https://user-images.githubusercontent.com/8396880/106560337-28f1d780-6527-11eb-9288-ce9f84e2f114.png">

Check the timestamp under DataFrame structure:

<img width="442" alt="Screen Shot 2021-02-02 at 07 19 31" src="https://user-images.githubusercontent.com/8396880/106560482-5fc7ed80-6527-11eb-8466-069fe51488d4.png">

**Comment by vaughanbrittonsage** [comment]
Thanks for the quick reply, I have checked the data and it does contain millisecond precision within the datetime string.

Hopefully the below screenshots will help to explain what I see:

![gantt-graph](https://user-images.githubusercontent.com/16590464/106619309-5f037b80-6568-11eb-8d90-303eb9e3e75f.PNG)
![gantt-data](https://user-images.githubusercontent.com/16590464/106619325-62970280-6568-11eb-8db0-e65edaf82055.PNG)

Thanks

**Comment by marcusolsson** [comment]
I see! It looks like you're losing precision when using string fields (instead of time or number field). I'll look into why, but depending on the data source you're using, could you try returning a number field with Unix epochs in ms instead?

**Comment by marcusolsson** [comment]
I've published 0.3.1 that contains a fix for this. Let me know if you're still having issues. Thanks again!
