### ISSUE TITLE
e.experiments is undefined on switch to gantt type panel

### ISSUE THREAD

**Issue by fiftyz** [marcusolsson/grafana-gantt-panel#64]
I get the following error when i try to switch to a gantt pannel type:

`An unexpected error happened
TypeError: e.experiments is undefined

zn@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:275:613
div
div
tr@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:393:492
div
t@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:3235
div
t@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:5186
_r@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:426:10798
div
div
ia@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:486:6049
v@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:971570
div
Mi@http://[Grafana IP]:3000/public/build/DashboardPage.fab5d6bbd438adca1160.js:574:3581
DashboardPage
v@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:971570
n@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:942013
zi@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:6393:193
t@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:989568
t@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:991589
main
t@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:986186
div
Ws@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:2156:1022
./public/app/core/utils/ConfigProvider.tsx/d<@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:4480:26183
Sl@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:2868:458
Tl@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:2868:1006
l@http://[Grafana IP]:3000/public/build/633.fab5d6bbd438adca1160.js:2:969086
Oo@http://[Grafana IP]:3000/public/build/7095.fab5d6bbd438adca1160.js:6473:384`

Grafana version: Grafana v8.3.1 (8d38082755)

**Comment by marcusolsson** [comment]
Thanks for reporting!

**Comment by fiftyz** [comment]
Thank you also, nice work, by the way! 👍

**Comment by marcusolsson** [comment]
Fix available in 0.7.5.
