### ISSUE TITLE
Dimension for Hover Text

### ISSUE THREAD

**Issue by Andi1986** [marcusolsson/grafana-gantt-panel#9]
Currently activities have hovertext which is showing start, end and duration.
A good addition would be to have dynamic hover text filled by a seperate **optional** dimension.
The field type for this dimension should be simple text with a defined maximum length.

See example use case here: #7

**Comment by marcusolsson** [comment]
What kind of information would like to show in the tooltip?

Here's an example of something similar from one of my other plugins, where you can select multiple fields to use as labels. 

<img width="1034" alt="Screen Shot 2021-02-03 at 20 50 06" src="https://user-images.githubusercontent.com/8396880/106800957-6b1f3400-6661-11eb-8e71-89a67dfa68bf.png">

Or, would you rather have paragraphs of text, with for example an error message?

**Comment by Andi1986** [comment]
this example is exactly how i thought it to be. i didnt have multiple fields in mind but actually i like that even more, so this would be perfect in my opinion

**Comment by marcusolsson** [comment]
Available in 0.4.0 🎉  Please try it and report any issues!

**Comment by Andi1986** [comment]
Hi, it looks almost good. i have error messages containg pretty long path, this makes the blue inner box overlap the toolbox, which looks a bit ugly. maybe you could fix that also. Thank you :)
